Nhid: []
Mhid:
- 256
- 256
alpha:
- 0.97
alpharp:
- 0.65
batch_size: 72
beta:
- 0.92
betas:
- 0.
- 0.95
burnin_steps: 100
chunk_size_test: 1800
chunk_size_train: 500
dataset: torchneuromorphic.dvs_gestures.dvsgestures_dataloaders
deltat: 1000
input_shape:
- 1
- 16
- 16
kernel_size:
- 1
lc_ampl: 0.5
learning_rate: 1.
learning_method: 'rtrl'
loss: smoothL1
lr_drop_factor: 5
lr_drop_interval: 30
num_epochs: 200
num_conv_layers: 0
num_mlp_layers: 2
num_layers: 2
num_dl_workers: 4
optimizer: adamax
out_channels: 11
online_update: True
pool_size:
- 2
- 1
- 2
random_tau: false
reg_l:
- .0
- .0
- .0
- .0
test_interval: 1
