Nhid: []
Mhid: 
- 200
- 200
- 200
- 200
alpha:
- 0.97
alpharp:
- 0.65
batch_size: 72
beta:
- 0.92
betas:
- 0.0
- 0.95
burnin_steps: 100
chunk_size_test: 1800
chunk_size_train: 500
dataset: decolle.datasets.load_dvsgestures_sparse
deltat: 1000
error_rate: 5.e-2
init_theta: 
- 1.e-06
- 1.e-06
- 1.e-06
- 1.e-06
input_shape:
- 2
- 32
- 32
kernel_size:
- 7
lc_ampl: 0.5
learning_rate: 1.0e-09
loss: mseloss #Not used
lr_drop_factor: 5
lr_drop_interval: 500
num_epochs: 2000
num_conv_layers: 0
num_mlp_layers: 4
num_layers: 4
optimizer: sgd #Not used
out_channels: 11
pool_size:
- 2
- 1
- 2
reg_l:
- .0
- .0
- .0
- .0
test_interval: 40
