Nhid:
Mhid:
- 1000
- 1000
- 1000
alpha:
- 0.97
alpharp:
- 0.65
batch_size: 200
beta:
- 0.92
betas:
- 0.0
- 0.95
burnin_steps: 30
chunk_size_test: 300
chunk_size_train: 300
dataset: torchneuromorphic.nmnist.nmnist_dataloaders
deltat: 1000
error_rate: 1.e-2
init_theta: 
- 1.e-06
- 1.e-06
- 1.e-06
input_shape:
- 2
- 32
- 32
kernel_size:
- 7
lc_ampl: 0.5
learning_rate: 1.0e-09
loss: smoothL1
lr_drop_factor: 2
lr_drop_interval: 10
num_layers: 3
num_epochs: 50
num_conv_layers: 0
num_mlp_layers: 3
num_dl_workers: 4
out_channels: 10
online_update: True
optimizer: sgd
pool_size:
random_tau: true
reg_l:
- .0
- .0
- .5
test_interval: 1
